config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'static_pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
            
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
            def new
                        @contact = Contact.new
            end

            def create
                        @contact = Contact.new(contact_params)
                        if @contact.valid? 
                                    redirect_to root_path
                        else
                                    render :new, status: :unprocessable_entity
                        end
                        

            end


private

def contact_params
            params.require(:contact).permit(:fname, :lname, :pnumber, :email)
end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
            def index
            end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/new.html.erb
<br />
<p>Contacts List</p>
<%= simple_form_for @contact do |f| %>
  <%= f.error_notification %>

  <%= f.input :fname %>
  <%= f.input :lname %>
  <%= f.input :pnumber %>

  <%= f.input :email, input_html: { autocomplete: 'email' } %>


  <%= f.button :submit, class: "btn-primary" %>
  <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<h2 style="color: blue"> Quiz 2 Project </h2>
 <%= link_to 'add contact', new_contact_path %>